//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateContentLayersOnPDFPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateContentLayersOnPDFPage.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;DANSK&lt;/div&gt;&lt;br/&gt;
        ///Denne kontorstol er testet til kontorbrug.
        ///Stolens mål klassificeres som type B i henhold
        ///til EN 1335-1.&lt;br/&gt;
        ///Hjulene er velegnede til alle gulve.&lt;br/&gt;
        ///&lt;div&gt;Vedligeholdelse&lt;/div&gt;&lt;br/&gt;
        ///Stel: Tørres af med en fugtig klud tilsat et
        ///mildt rengøringsmiddel. Tør efter med en
        ///ren klud.&lt;br/&gt;
        ///Stofbetræk: Mindre pletter kan fjernes med
        ///tekstilrens eller en fugtig svamp og en mild
        ///sæbeopløsning.&lt;br/&gt;
        ///Læderbetræk: Støvsuges. Beskyttes mod
        ///direkte sollys for at forhindre udtørring. For [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dansk {
            get {
                return ResourceManager.GetString("Dansk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;DEUTSCH&lt;/div&gt;&lt;br/&gt;
        ///Dieser Stuhl ist für den Bürogebrauch
        ///getestet. Die Maße sind gem. EN 1335-1 als
        ///Typ B eingestuft.&lt;br/&gt;
        ///Die Rollen eignen sich für alle Bodenbeläge.&lt;br/&gt;
        ///&lt;div&gt;Pflegehinweis&lt;/div&gt;&lt;br/&gt;
        ///Gestell: Mit feuchtem Tuch mit mildem
        ///Reinigungsmittel abwischen. Mit trockenem
        ///Tuch nachwischen.&lt;br/&gt;
        ///Stoffbezug: Leichte Flecken mit Textilreinigungsmittel
        ///oder mit feuchtem Schwamm,
        ///evtl. mit milder Seifenlauge entfernen.&lt;br/&gt;
        ///Lederbezug: Staubsaugen. Vor direkter
        ///Sonneneinstrahlung schü [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deutch {
            get {
                return ResourceManager.GetString("Deutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;ENGLISH&lt;/div&gt;&lt;br/&gt;
        ///This office work chair is tested for office
        ///use. The dimensions of this chair are classified
        ///as Type B according to EN 1335-1.
        ///The castors are suitable for any type of
        ///floor.&lt;br/&gt;
        ///&lt;div&gt;Care instructions&lt;/div&gt;&lt;br/&gt;
        ///Frame: Wipe clean with a mild soapy solution.
        ///Wipe dry with a clean cloth.&lt;br/&gt;
        ///Fabric cover: Light stains can be removed
        ///with a textile cleaner or a damp sponge and
        ///a mild soapy solution.&lt;br/&gt;
        ///Leather cover: Vacuum clean. Protect from
        ///direct sunlight to preven [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;FRANÇAIS&lt;/div&gt;&lt;br/&gt;
        ///Cette chaise de bureau professionnel a été
        ///testée pour un usage professionnel. Les
        ///dimensions de cette chaise la classent dans
        ///le Type B selon la norme EN 1335-1.
        ///Les roulettes peuvent s’utiliser sur tout
        ///type de sol.&lt;br/&gt;
        ///&lt;div&gt;Instructions d’entretien&lt;/div&gt;&lt;br/&gt;
        ///Structure : nettoyer avec une solution
        ///savonneuse, puis essuyer avec un chiffon
        ///sec.&lt;br/&gt;
        ///Housse en tissu : les petites taches
        ///peuvent être retirées à l’aide d’un nettoyant
        ///pour textile ou d’une éponge trempée  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Français {
            get {
                return ResourceManager.GetString("Français", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;ITALIANO&lt;/div&gt;&lt;br/&gt;
        ///Questa sedia da ufficio è testata per l’uso
        ///negli uffici. Per le sue dimensioni, questa
        ///sedia è classificata di tipo B, secondo la
        ///norma EN 1335-1.&lt;br/&gt;
        ///Le rotelle sono adatte a tutti i tipi di superfici.&lt;br/&gt;
        ///&lt;div&gt;Manutenzione&lt;/div&gt;&lt;br/&gt;
        ///Struttura: pulisci con una soluzione di
        ///acqua e sapone poco concentrata. Asciuga
        ///con un panno pulito.&lt;br/&gt;
        ///Rivestimento in tessuto: le macchie leggere
        ///si possono eliminare con un detergente per
        ///tessuti o con una spugna inumidita con acq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Italiano {
            get {
                return ResourceManager.GetString("Italiano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;NEDERLANDS&lt;/div&gt;&lt;br/&gt;
        ///Deze bureaustoel is getest voor gebruik
        ///op kantoor. De afmetingen van de stoel
        ///zijn geclassificeerd als Type B volgens EN
        ///1335-1.&lt;br/&gt;
        ///De wielen zijn geschikt voor alle soorten
        ///vloeren.&lt;br/&gt;
        ///&lt;div&gt;Onderhoud&lt;/div&gt;&lt;br/&gt;
        ///Onderstel: afnemen met een doekje met
        ///wat mild schoonmaakmiddel. Nadrogen met
        ///een droge doek.&lt;br/&gt;
        ///Stoffen bekleding: lichte vlekken kunnen
        ///worden verwijderd met textielreiniger of
        ///met een sponsje met water of een milde
        ///zeepoplossing.&lt;br/&gt;
        ///Leren bekledi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nederlands {
            get {
                return ResourceManager.GetString("Nederlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;РУССКИЙ&lt;/div&gt;&lt;br/&gt;
        ///Этот рабочий стул протестирован и
        ///одобрен для использования в офисе.
        ///Размеры этого стула классифицируются
        ///как Тип В в соответствии со стандартом
        ///EN 1335-1.&lt;br/&gt;
        ///Колесики подходят для любого типа
        ///напольных покрытий.&lt;br/&gt;
        ///&lt;div&gt;Инструкции по уходу&lt;/div&gt;&lt;br/&gt;
        ///Каркас: протирать с использованием
        ///слабого мыльного раствора. Затем
        ///вытирать сухой чистой тканью.&lt;br/&gt;
        ///Текстильная обивка: слабые загрязнения
        ///можно удалить чистящим средством
        ///для текстиля или с помощью губки,
        ///смоченно [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Русский {
            get {
                return ResourceManager.GetString("Русский", resourceCulture);
            }
        }
    }
}
